//
// Created by YUAN on 2026/4/18.
//

#ifndef SHELLCODE_FRAME_CONSTANT_MACRO_H
#define SHELLCODE_FRAME_CONSTANT_MACRO_H

#define FRAME_INFINITE 0xffffffff
#define FRAME_WINHTTP_FLAG_SECURE 0x00800000
#define FRAME_WINHTTP_ACCESS_TYPE_DEFAULT_PROXY 0

#define FRAME_PAGE_NOACCESS 0x01
#define FRAME_PAGE_READONLY 0x02
#define FRAME_PAGE_READWRITE 0x04
#define FRAME_PAGE_EXECUTE 0x10
#define FRAME_PAGE_EXECUTE_READ 0x20
#define FRAME_PAGE_EXECUTE_READWRITE 0x40

#define FRAME_MEM_COMMIT 0x1000
#define FRAME_MEM_RESERVE 0x2000
#define FRAME_MEM_RELEASE 0x8000

#endif //SHELLCODE_FRAME_CONSTANT_MACRO_H